CREATE TABLE public.profiles(
  id uuid PRIMARY KEY,
  tipo text NOT NULL CHECK (tipo IN ('f','e')),
  empresa text NOT NULL,
  email text,
  categoria text,
  cidade text,
  is_seed boolean NOT NULL DEFAULT false,
  criado_em timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE ON public.profiles TO authenticated;
GRANT ALL ON public.profiles TO service_role;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "profiles read" ON public.profiles FOR SELECT TO authenticated USING (true);
CREATE POLICY "profiles insert own" ON public.profiles FOR INSERT TO authenticated WITH CHECK (id = auth.uid() AND is_seed = false);
CREATE POLICY "profiles update own" ON public.profiles FOR UPDATE TO authenticated USING (id = auth.uid()) WITH CHECK (id = auth.uid() AND is_seed = false);

CREATE TABLE public.profiles_private(
  id uuid PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  documento text,
  documento_tipo text NOT NULL DEFAULT 'cnpj',
  telefone text
);
GRANT SELECT, INSERT, UPDATE ON public.profiles_private TO authenticated;
GRANT ALL ON public.profiles_private TO service_role;
ALTER TABLE public.profiles_private ENABLE ROW LEVEL SECURITY;
CREATE POLICY "priv own select" ON public.profiles_private FOR SELECT TO authenticated USING (id = auth.uid());
CREATE POLICY "priv own insert" ON public.profiles_private FOR INSERT TO authenticated WITH CHECK (id = auth.uid());
CREATE POLICY "priv own update" ON public.profiles_private FOR UPDATE TO authenticated USING (id = auth.uid());

CREATE OR REPLACE FUNCTION public.meu_tipo() RETURNS text LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS
$$ SELECT tipo FROM public.profiles WHERE id = auth.uid() $$;

CREATE TABLE public.produtos(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fornecedor_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  nome text NOT NULL,
  preco numeric(12,2) NOT NULL CHECK (preco > 0),
  unidade text NOT NULL DEFAULT 'unidade',
  qtd_min integer NOT NULL DEFAULT 1,
  categoria text,
  descricao text,
  icone text NOT NULL DEFAULT 'box',
  views integer NOT NULL DEFAULT 0,
  criado_em timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.produtos TO authenticated;
GRANT ALL ON public.produtos TO service_role;
ALTER TABLE public.produtos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "produtos read" ON public.produtos FOR SELECT TO authenticated USING (true);
CREATE POLICY "produtos insert" ON public.produtos FOR INSERT TO authenticated WITH CHECK (fornecedor_id = auth.uid() AND public.meu_tipo() = 'f');
CREATE POLICY "produtos update" ON public.produtos FOR UPDATE TO authenticated USING (fornecedor_id = auth.uid());
CREATE POLICY "produtos delete" ON public.produtos FOR DELETE TO authenticated USING (fornecedor_id = auth.uid());

CREATE TABLE public.favoritos(
  user_id uuid NOT NULL,
  produto_id bigint NOT NULL REFERENCES public.produtos(id) ON DELETE CASCADE,
  PRIMARY KEY(user_id, produto_id)
);
GRANT SELECT, INSERT, DELETE ON public.favoritos TO authenticated;
GRANT ALL ON public.favoritos TO service_role;
ALTER TABLE public.favoritos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "fav own" ON public.favoritos FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

CREATE TABLE public.mensagens(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  de_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  para_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  texto text NOT NULL CHECK (length(texto) BETWEEN 1 AND 2000),
  criado_em timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT ON public.mensagens TO authenticated;
GRANT ALL ON public.mensagens TO service_role;
ALTER TABLE public.mensagens ENABLE ROW LEVEL SECURITY;
CREATE POLICY "msg read" ON public.mensagens FOR SELECT TO authenticated USING (de_id = auth.uid() OR para_id = auth.uid());
CREATE POLICY "msg send" ON public.mensagens FOR INSERT TO authenticated WITH CHECK (de_id = auth.uid() AND para_id <> auth.uid());

CREATE TABLE public.pedidos(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  produto_id bigint NOT NULL REFERENCES public.produtos(id) ON DELETE CASCADE,
  empresario_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  qtd integer NOT NULL,
  status text NOT NULL DEFAULT 'Em negociação' CHECK (status IN ('Em negociação','Aguardando envio','Enviado','Recusado')),
  criado_em timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT ON public.pedidos TO authenticated;
GRANT ALL ON public.pedidos TO service_role;
ALTER TABLE public.pedidos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "ped read" ON public.pedidos FOR SELECT TO authenticated USING (
  empresario_id = auth.uid() OR EXISTS (SELECT 1 FROM public.produtos p WHERE p.id = produto_id AND p.fornecedor_id = auth.uid()));
CREATE POLICY "ped insert" ON public.pedidos FOR INSERT TO authenticated WITH CHECK (
  empresario_id = auth.uid() AND public.meu_tipo() = 'e' AND status = 'Em negociação');

-- RPCs
CREATE OR REPLACE FUNCTION public.ver_produto(_id bigint) RETURNS void LANGUAGE sql SECURITY DEFINER SET search_path = public AS
$$ UPDATE public.produtos SET views = views + 1 WHERE id = _id $$;
GRANT EXECUTE ON FUNCTION public.ver_produto(bigint) TO authenticated;

CREATE OR REPLACE FUNCTION public.mudar_status(_id bigint, _status text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF _status NOT IN ('Em negociação','Aguardando envio','Enviado','Recusado') THEN RAISE EXCEPTION 'Status inválido'; END IF;
  UPDATE public.pedidos o SET status = _status FROM public.produtos p
   WHERE o.id = _id AND p.id = o.produto_id AND p.fornecedor_id = auth.uid();
  IF NOT FOUND THEN RAISE EXCEPTION 'Pedido inválido'; END IF;
END $$;
GRANT EXECUTE ON FUNCTION public.mudar_status(bigint, text) TO authenticated;

CREATE OR REPLACE FUNCTION public.auto_resposta() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM public.profiles WHERE id = NEW.para_id AND is_seed) THEN
    INSERT INTO public.mensagens(de_id, para_id, texto) VALUES (NEW.para_id, NEW.de_id, 'Recebemos sua mensagem! Posso te enviar uma proposta.');
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_auto_resposta AFTER INSERT ON public.mensagens FOR EACH ROW EXECUTE FUNCTION public.auto_resposta();

-- Seed
INSERT INTO public.profiles(id,tipo,empresa,categoria,cidade,is_seed) VALUES
('00000000-0000-0000-0000-000000000001','f','Distribuidora Campo Forte','Alimentos','Campinas, SP',true),
('00000000-0000-0000-0000-000000000002','f','Café do Vale','Alimentos','Poços de Caldas, MG',true),
('00000000-0000-0000-0000-000000000003','f','Limpa Mais Atacado','Limpeza','Curitiba, PR',true),
('00000000-0000-0000-0000-000000000004','f','Malha Sul Confecções','Roupas','Blumenau, SC',true),
('00000000-0000-0000-0000-000000000005','f','Volt Atacado','Eletrônicos','São Paulo, SP',true);

INSERT INTO public.produtos(fornecedor_id,nome,preco,unidade,qtd_min,categoria,descricao,icone) VALUES
('00000000-0000-0000-0000-000000000005','Pilha Alcalina AA',96.00,'caixa',2,'Eletrônicos','Caixa com 48 pilhas AA, validade de 5 anos.','battery'),
('00000000-0000-0000-0000-000000000005','Lâmpada LED 9 W Bivolt',215.00,'caixa',2,'Eletrônicos','Caixa com 50 lâmpadas E27, luz branca 6500 K, vida útil de 15 mil horas.','bulb'),
('00000000-0000-0000-0000-000000000005','Carregador USB-C 20 W',14.50,'unidade',50,'Eletrônicos','Carregador de parede com carga rápida, bivolt, 1 ano de garantia.','plug'),
('00000000-0000-0000-0000-000000000004','Camisa Polo Uniforme',38.00,'peça',20,'Roupas','Piquet com gola e punhos, cores sob consulta, bordado opcional.','shirt'),
('00000000-0000-0000-0000-000000000004','Camiseta Algodão Penteado',19.90,'peça',30,'Roupas','Malha 30.1 penteada, lisa, tamanhos P ao GG. Ótima para estampa.','shirt'),
('00000000-0000-0000-0000-000000000003','Saco de Lixo 100 L Reforçado',69.00,'pacote',6,'Limpeza','Pacote com 100 sacos pretos de 100 litros, resistente a 20 kg.','bag'),
('00000000-0000-0000-0000-000000000003','Desinfetante Floral 5 L',24.90,'galão',12,'Limpeza','Galão de 5 litros, concentrado. Rende até 1:10 de diluição.','bottle'),
('00000000-0000-0000-0000-000000000003','Detergente Líquido Neutro 500 ml',54.00,'caixa',5,'Limpeza','Caixa com 24 frascos de 500 ml. Neutro, biodegradável.','bottle'),
('00000000-0000-0000-0000-000000000001','Milho Verde em Conserva 170 g',62.00,'caixa',4,'Alimentos','Caixa com 24 latas de 170 g. Grãos selecionados, pronto para uso.','can'),
('00000000-0000-0000-0000-000000000002','Café Torrado e Moído 500 g',310.00,'caixa',2,'Alimentos','Caixa com 20 pacotes a vácuo de 500 g. Torra média, 100% arábica.','coffee'),
('00000000-0000-0000-0000-000000000001','Óleo de Soja 900 ml',128.00,'caixa',3,'Alimentos','Caixa com 20 garrafas de 900 ml. Refinado, validade mínima de 8 meses.','droplet'),
('00000000-0000-0000-0000-000000000001','Feijão Carioca Tipo 1 – 1 kg',58.00,'fardo',10,'Alimentos','Fardo com 10 pacotes de 1 kg. Safra recente, baixo índice de grãos quebrados.','sack'),
('00000000-0000-0000-0000-000000000001','Arroz Agulhinha Tipo 1 – 5 kg',142.00,'fardo',5,'Alimentos','Fardo com 6 pacotes de 5 kg (30 kg). Grãos soltos, ideal para restaurantes e mercados.','sack');