CREATE TABLE public.avaliacoes(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id bigint NOT NULL UNIQUE REFERENCES public.pedidos(id) ON DELETE CASCADE,
  fornecedor_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  empresario_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  nota smallint NOT NULL CHECK (nota BETWEEN 1 AND 5),
  comentario text CHECK (comentario IS NULL OR length(comentario) <= 1000),
  criado_em timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT ON public.avaliacoes TO authenticated;
GRANT ALL ON public.avaliacoes TO service_role;
ALTER TABLE public.avaliacoes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "aval read" ON public.avaliacoes FOR SELECT TO authenticated USING (true);
CREATE POLICY "aval insert" ON public.avaliacoes FOR INSERT TO authenticated WITH CHECK (
  empresario_id = auth.uid() AND EXISTS (
    SELECT 1 FROM public.pedidos o JOIN public.produtos p ON p.id = o.produto_id
    WHERE o.id = pedido_id AND o.empresario_id = auth.uid() AND o.status = 'Enviado' AND p.fornecedor_id = avaliacoes.fornecedor_id));